data/holiday_database/de-hb/2020.json

Feriendaten aktualisiert

---

data/holiday_database/de-th/info.json

Update Thüringen info.json

---

data/holiday_database/de-th/2021.json

create Thüringen 2021.json

---

data/holiday_database/de-st/2020.json

updated holidays school year 2020/21

Update Sachsen-Anhalt 2020.json

---

data/holiday_database/de-st/2021.json

Create Sachen-Anhalt 2021.json

---

data/holiday_database/de-bb/2020.json
data/holiday_database/de-bb/2021.json
data/holiday_database/de-bb/info.json
data/holiday_database/de-be/2020.json
data/holiday_database/de-be/2021.json
data/holiday_database/de-be/info.json
data/holiday_database/de-bw/2020.json
data/holiday_database/de-bw/2021.json
data/holiday_database/de-bw/info.json
data/holiday_database/de-hb/2020.json
data/holiday_database/de-hb/2021.json
data/holiday_database/de-hb/info.json

Bitte um Überprüfung, da verschiedene Quellen verschiedene Daten angeben! Am besten sollte jemand, der in dem jeweiligen Bundesland lebt und zur Schule geht, die Daten überprüfen.

Holiday DB update for Brandenburg, Berlin, Baden-Württemberg and Bremen

---

data/holiday_database/de-st/info.json

Update Sachsen-Anhalt info.json

---

data/holiday_database/de-st/2021.json

Create Sachsen-Anhalt 2021.json

---

data/holiday_database/de-sn/info.json

added year "2020" and updated last refreshed date

Update Sachsen info.json

---

data/holiday_database/de-sn/2021.json

added holidays school year 2020/21

Create Sachsen 2021.json

---

data/holiday_database/de-sn/2020.json

updated holidays school year 2020/21

Update Sachsen 2020.json

---

data/holiday_database/de-th/2020.json

updated holidays for school year 2020/21

Update Thüringen 2020.json

---

data/holiday_database/de-rp/info.json

Update rp info.json

---

data/holiday_database/de-rp/2021.json

Create rp 2021.json

---

data/holiday_database/de-rp/2020.json

updated holidays for school year 2020/21

Update rp 2020.json

---

data/holiday_database/de-sh/2021.json

create sh 2021.json

---

data/holiday_database/de-st/2021.json

Update st 2021.json

---

data/holiday_database/de-sh/2020.json

updated holidays for school year 2020/21

Update sh 2020.json

---

data/holiday_database/de-sl/info.json

Update sl info.json

---

data/holiday_database/de-sl/2020.json

update holidays for school year 2020/21

Update Sl 2020.json

---

data/holiday_database/at-1/2021.json

create at-1 2021.json

---

data/holiday_database/at-8/2020.json

create at-8 2020.json

---

data/holiday_database/at-9/2021.json

create at-9 2021.json

---

data/holiday_database/at-9/2020.json

create at-9 2020.json

---

data/holiday_database/at-9/info.json

Update at-9 info.json

---

data/holiday_database/at-8/2021.json

create at-8 2021.json

---

data/holiday_database/de-ni/info.json

Update ni info.json

---

data/holiday_database/de-by/info.json

Update by info.json

---

data/holiday_database/de-by/2021.json

create by 2021.json

---

data/holiday_database/at-1/2020.json

create at-1 2020.json

---

data/holiday_database/at-1/info.json

added years "2020; 2021" and updated last refreshed date

Update at-1 info.json

---

data/holiday_database/at-2/2020.json

create at-2 2020.json

---

data/holiday_database/de-sl/2021.json

create sl 2021.json

---

data/holiday_database/de-sh/info.json

Update sh info.json

---

data/holiday_database/de-ni/2021.json

create ni 2021.json

---

data/holiday_database/at-2/2021.json

Create at-2 2021.json

---

data/holiday_database/at-3/info.json

Update at-3 info.json

---

data/holiday_database/at-3/2021.json

create at-3 2021.json

---

data/holiday_database/at-2/info.json

Update at-2 info.json

---

data/holiday_database/at-3/2020.json

create at-3 2020.json

---

data/holiday_database/at-4/2021.json

create at-4 2021.json

---

data/holiday_database/at-5/2020.json

added holiays for school year 2020/21

Create at-5 2020.json

---

data/holiday_database/at-4/info.json

Update at-4 info.json

---

data/holiday_database/at-5/info.json

Update at-5 info.json

---

data/holiday_database/at-5/2021.json

create at-5 2021.json

---

data/holiday_database/at-7/2021.json

create at-7 2021.json

---

data/holiday_database/at-6/info.json

Update at-6 info.json

---

data/holiday_database/at-6/2021.json

create at-6 2021.json

---

data/holiday_database/at-7/2020.json

create at-7 2020.json

---

data/holiday_database/at-6/2020.json

create at-6 2020.json

---

data/holiday_database/at-7/info.json

Update at-7 info.json

---

data/holiday_database/at-8/info.json

Update at-8 info.json

---

data/holiday_database/de-he/2021.json

Added the year 2021 for Hessen, Germany

Created 2021.json

---

README.md

[contributing]: https://github.com/flowhorn/schulplaner/blob/master/CONTRIBUTING.md
Closes Issue: NaN
Replace this sentence with general description of what your Pull Request does.

added structure to the readme

---

README.md

added instructions on how to run the app

---

app/lib/Views/SchoolPlanner/Library.dart

#145
[contributing]: https://github.com/flowhorn/schulplaner/blob/master/CONTRIBUTING.md
- [ x] I have checked the PRs for upcoming features/bug fixes.
- [ x] I have read the [contributing guidelines][contributing].
- [x ] Internal code
Closes Issue: #145 
This centers the buttons inside the ButtonBar

Centers the children in ButtonBar

---

app/lib/Views/SchoolPlanner/Library.dart
app/lib/Views/SchoolPlanner/holidays/holiday_list.dart
app/lib/Views/SchoolPlanner/planner_settings/holiday_settings.dart
app/lib/holiday_database/logic/holiday_gateway.dart
app/lib/holiday_database/models/holiday.dart

[contributing]: https://github.com/flowhorn/schulplaner/blob/master/CONTRIBUTING.md
Closes Issue: NaN
Feriendatenbank-Cache auf 21 Tage erhöht,
kein Laden von Ferien von vorletzem Jahr mehr
Verbesserte Darstellung vergangener Ferien

changed little details to ui + longer cache duration/improvements

---

README.md

Cherry-picking 2957a94 from develop to update readme on defualt branch.

update contact section
